### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [gary9630/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the page looks good. You used some good techniques here and kept your code organized. Take a look at the issues I created, they will give your some tips on organization and efficiency. The next part of the course is going to have much larger more complex projects and it will be important to be efficient and organized. Here are some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by gary9630** [comment]
Thank you again for reviewing my code hand in lately and providing me some useful information. This is the first time I learn how to write the websites and this course is excellent so far.
